ittapi-rs/build.rs
@jlb6740, this is what I had to do to get this to build on Fedora 31 (kernel: 5.8.8-100.fc31.x86_6), . What do you think?
=> fix: compiled library should not have '64' appended

src/ittnotify/ittnotify_static.c
`={0}` has slightly different semantics with C and C++. In this particular case, we can rely on zero initialization of objects with static storage duration.
=> Remove C style nullification

src/ittnotify/ittnotify_config.h
ITTAPI is used by [oneDNN](https://github.com/oneapi-src/oneDNN)
Updating ITTAPI version to v3.20.1 introduced warning on oneDNN side about implicit declaration of strdup():
```
src/common/ittnotify/ittnotify_static.c:606:8: warning: implicit declaration of function 'strdup' is invalid in C99 [-Wimplicit-function-declaration]
NEW_COUNTER_A(&_N_(_ittapi_global),h,h_tail,name,domain,type);
^
```
The reason is that `strdup()` is not part of C99 which results in a warning. To avoid the issue this PR adds an explicit implementation of `strdup()`. Unfortunately, since it is part of `ittnotify_config.h` I couldn't define a function there because it doesn't contain headers required for `malloc()`, `strlen()` and `strcpy()` symbols, so I had to modify users of strdup() to make use of macro. This …
=> implement strdup() to avoid warnings about implicit declaration on linux

src/ittnotify/disable_warnings.h
This matches other such ifdefs added in f42078d6.
This silences warnings when built in MinGW mode (as part of
the OpenMP runtime).
=> Only use #pragma warning on MSVC on Windows

src/ittnotify/ittnotify_static.c
__itt_get_lib_name() is called each time when ITT API instance is created. Environment variable
(for example, path to itt-library) is stored in static buffer and can be accessed by pointer.
The next environment variable will be stored to this buffer by offset not to overlap previous one.
Creating of many ITT API instances can lead to error report through __itt_report_error()
and/or absence of ITT API data.
So, check ITT collector existance before calling __itt_get_lib_name().
=> Fix ITT API initialization issue

ittapi-rs/Cargo.toml, ittapi-rs/README.md
This change updates the README with more up-to-date information,
expanding several sections, and adding some new ones. It also adds the
`readme` field to `Cargo.toml` so that this information will show up on
https://crates.io/crates/ittapi-rs. It also updates the bindgen
dependency.
=> Improve README, publish README to crates.io

ittapi-rs/src/ittnotify_bindings.rs, ittapi-rs/src/jitprofiling_bindings.rs
The `ittapi` bindings have changed slightly and this change regenerates
them from the latest header files.
=> Update the ittapi Rust bindings

ittapi-rs/Cargo.toml
This change allows us to publish the latest changes to crates.io.
=> Bump ittapi-rs version

ittapi-rs/README.md, ittapi-rs/build.rs
Since #32, we no longer need to mention CMake as a dependency.
=> Remove CMake documentation from Rust bindings

ittapi-rs/build.rs
As discussed in #32, change 8601f82 no longer sets a different name for
32- and 64-bit builds of the `ittapi` library. This change does the same
for the Rust build script.
=> rust: remove `32` and `64` postfix when in lib name

ittapi-rs/.gitignore, ittapi-rs/README.md, ittapi-rs/scripts/copy-c-library.ps1
The Rust crate uses a POSIX symlink for accessing the C library files.
On Windows this may not work so we document two workarounds.
=> rust: add a workaround for developing the Rust crate on Windows

.github/workflows/rust.yml
Recursively removing the `C:\msys64` directory on the Windows GitHub
runners was taking upwards of 25 minutes. This change simply renames it
to avoid shadowing the `libclang.dll` name in the path.
=> ci: rename mingw directory

.github/workflows/rust.yml, ittapi-rs/CHANGELOG.md, ittapi-rs/Cargo.toml
Recent changes to enable Windows support have slightly altered the
bindings, which changes the public API. These are not breaking changes
but a minor version bump seems appropriate, especially with the new OS
support.
=> rust: bump version to v0.2.0

ittapi-rs/integration-tests/Cargo.toml, ittapi-rs/integration-tests/README.md, ittapi-rs/integration-tests/src/main.rs, ittapi-rs/integration-tests/tests/main.rs, ittapi-rs/ittapi-sys/README.md, ittapi-rs/ittapi-sys/src/lib.rs, ittapi-rs/ittapi/Cargo.toml, ittapi-rs/ittapi/README.md, ittapi-rs/ittapi/src/domain.rs, ittapi-rs/ittapi/src/event.rs, ittapi-rs/ittapi/src/jit.rs, ittapi-rs/ittapi/src/lib.rs, ittapi-rs/ittapi/src/string.rs, ittapi-rs/ittapi/src/task.rs, ittapi-rs/ittapi/src/util.rs
This change refactors the code @bnjbvr added to the `ittapi` crate to support a few new ITT APIs: domains, tasks, events, string handles (a full list is available [here](https://www.intel.com/content/www/us/en/develop/documentation/vtune-help/top/api-support/instrumentation-and-tracing-technology-apis/instrumentation-tracing-technology-api-reference.html)). It also improves the documentation and adds tests for the new APIs. Another addition is an `integration-test` crate that checks that a system configured with VTune will be able to actually collect data using the Rust crate.
=> rust: add more APIs to the new high-level `ittapi` crate

.github/workflows/main.yml, rust/scripts/.gitignore, rust/scripts/verify-publish.sh
With the split to two crates, the CI should now check that both can be packaged up for publishing.
=> ci: check that both Rust crates are publishable

rust/CHANGELOG.md, rust/ittapi-sys/Cargo.toml, rust/ittapi/Cargo.toml
This PR will bump the versions of the now-separate `ittapi` and
`ittapi-sys` crates to 0.3.0. Once published, we will separately
deprecate the `ittapi-rs` crate by changing the README to a deprecation
notice. Also, this updates the few dependencies of these crates.
=> rust: release the `ittapi` and `ittapi-sys` crates

rust/ittapi-sys/scripts/copy-c-library.ps1, rust/scripts/copy-c-library.ps1
With the move to two crates, the paths to copy the c-library files needed updating.
=> rust: fix PowerShell script paths

rust/ittapi/src/domain.rs
As discussed in the [ITT documentation], the `__itt_domain` structure
that `Domain` is based on can be accessed by any thread.
[ITT documentation]: https://www.intel.com/content/www/us/en/develop/documentation/vtune-help/top/api-support/instrumentation-and-tracing-technology-apis/instrumentation-tracing-technology-api-reference/domain-api.html
=> rust: make `Domain` a `Sync` structure

.github/workflows/main.yml, rust/clippy.toml, rust/ittapi-sys/Cargo.toml, rust/ittapi-sys/build.rs, rust/ittapi-sys/src/lib.rs, rust/ittapi/Cargo.toml, rust/ittapi/src/event.rs, rust/ittapi/src/jit.rs, rust/ittapi/src/lib.rs, rust/ittapi/src/string.rs, rust/ittapi/src/task.rs, rust/ittapi/src/util.rs
This change turns on clippy static analysis during CI runs. Many of the
changes to make this pass are pedantic, but some are interesting (e.g.,
integer truncation, better documentation, clearer error handling).
=> rust: turn on clippy in CI

rust/CHANGELOG.md, rust/ittapi-sys/Cargo.toml, rust/ittapi/Cargo.toml
Include all recent changes in a new release for external use.
=> rust: release 0.3.1

.github/workflows/main.yml
Now that https://github.com/actions/virtual-environments/pull/5729 has
merged, GitHub runners using `windows-latest` (i.e., Windows 2022)
should have a later version of MinGW (i.e., 11.2.0) that solves the
build issues observed in this repository. Recall that the `strnlen_s`
function is not available on older versions of MinGW but was necessary
to compile the C library. With this change, CI will use GitHub's MinGW
version instead of manually installing a new one.
=> ci: use GitHub's updated version of MinGW

CMakeLists.txt
Set `cmake_policy` CMP0048 to NEW before `project` command to suppress the following warning introduced in CMake 3.22:
```
CMake Warning (dev) at CMakeLists.txt:9 (project):
Policy CMP0048 is not set: project() command manages VERSION variables.
Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
The following variable(s) would be set to empty:
CMAKE_PROJECT_VERSION
CMAKE_PROJECT_VERSION_MAJOR
CMAKE_PROJECT_VERSION_MINOR
CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.
```
NEW policy sets `VERSION` variables to empty values, while `OLD` policy leaves them unchanged. Please note that setting policy to `OLD` results in deprecated warning saying that it will be …
=> Suppress CMake policy warning (CMP0048)

rust/deny.toml, rust/ittapi/src/string.rs
Previously, the `string::with_dynamic_part_specified` test did not set up the environment as it should, relying instead on user action for the test to pass.
=> rust: use `scoped-env` crate in test

include/ittnotify.h
This misspelling was found by @AnuyaWelling2801 in #67; closes #67.
=> Fix spelling of doc comment

rust/ittapi-sys/Cargo.toml, rust/ittapi/Cargo.toml, rust/scripts/verify-publish.sh
Bump the version of the Rust crates in preparation for a new release with the new "collection control" API.
=> rust: release v0.3.2

rust/CHANGELOG.md, rust/ittapi-sys/Cargo.toml, rust/ittapi-sys/README.md, rust/ittapi/Cargo.toml, rust/ittapi/README.md
Bump the version of the Rust crates to release FreeBSD support.
=> rust: release v0.3.3

rust/ittapi-sys/Cargo.toml
This removes files like the `.git` history from the packaged files. Verified with `cargo package --list`.
=> rust: exclude unnecessary files from `ittapi-sys` crate

rust/ittapi/src/jit.rs
The documentation of the `iJIT_METHOD_LOAD` event states that when calling into `notify_event` with that event, the return type is undefined, so we can't really tell whether that worked or not. So far, the library assumed that this would return 1, which is only the case when the event type is `SHUTDOWN`. This PR fixes that.
Also, avoid a double shutdown. I don't know if this prevents actual issues, but better be safe than sorry.
=> rust: improve error checking and avoid double shutdown

buildall.py
This runs the standard PEP 8 formatter on `buildall.py`--no logic changes included.
=> ci: format `buildall.py`

rust/ittapi-sys/Cargo.toml
There are several precompiled fortran object files included in the rust package that are completely unnecessary, bloating the package.
=> Remove large and unnecessary fortran objects

rust/ittapi-sys/tests/bindgen-up-to-date.rs
This removes a deprecation warning related to the previous function, `bindgen::Builder::rustfmt_bindings`.
=> rust: use new `bindgen::Builder::formatter` method

rust/Cargo.toml
This eliminates some unnecessary Cargo warnings.
=> rust: specify Cargo resolver

rust/ittapi/src/jit.rs
Previously, the Rust bindings used the `iJVM_EVENT_TYPE_METHOD_INLINE_LOAD_FINISHED` event to notify VTune of new JIT code. This may not be correct: it is unclear from the documentation, but an "inline JIT-compiled method" sounds more like self-modifying code, not typically what we think of with JIT-compiled code. JIT-compiled code, as used elsewhere (e.g., Wasmtime), is typically emitted in a memory allocation that is separate from the runtime binary code region. This change uses the `iJVM_EVENT_TYPE_METHOD_LOAD_FINISHED` event instead.
=> rust: use a different `METHOD_LOAD` event

.github/dependabot.yml, .github/workflows/codeql.yml, .github/workflows/main.yml, .github/workflows/release.yml
Adds some changes for improving security. Motivation was to improve score as tracked by https://github.com/ossf/scorecard . 
The tool at https://app.stepsecurity.io/securerepo is used for identifying the required changes, and the bot helped create the base commit, as recommended by Scorecard.
The GITHUB_TOKEN is an automatically generated secret to make authenticated calls to the GitHub API. GitHub recommends setting minimum token permissions for the GITHUB_TOKEN.
- [GitHub Security Guide](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow)
- [The Open Source Security Foundation (OpenSSF) Security Guide](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions)
GitHub Action tags and Docker tags are …
=> Add security best practices

src/ittnotify_refcol/itt_refcol_impl.c
We allocate memory for the `log_file`  via malloc in `log_file_name_generate()` but do not free it
=> Fix memory leak in reference collector

rust/ittapi/README.md
- use `*` for the version to avoid getting out of date
- link to some code examples of how to use the `ittapi` crate
=> rust: improve the landing page documentation for crates.io

rust/ittapi/src/string.rs
PR #69 identified an issue with how the C library gives out string handles: it only does so when `INTEL_LIBITTNOTIFY64` is present in the environment. This change clarifies this in the test, though presumably at some point the C library should not be handing out null pointers or `StringHandle::new` should fail with a coherent error message.
=> rust: improve `StringHandle` test

.github/dependabot.yml
PR #107 introduced dependabot to the repository to update GitHub Actions. This results in a weekly stream of PRs to incorporate every tiny patch update for every GitHub Action we use here. This results in a lot of churn and I do not have any sense that it improves the code quality in any way. Instead, it may in fact be the cause of the breakage in the release workflow, since that relies on `upload-artifact` which dependabot bumped from v3.1.3 to v4.0.0 (see #126).
What this change does is follow GitHub's [guidance] to only receive security updates. Since "dependabot security updates" are enabled, we don't need to follow each action update; setting
`open-pull-requests-limit` to 0 mutes the dependabot PRs but we should still see any security alerts in the security tab.
[guidance]: …
=> ci: reduce the steady stream of dependabot PRs

src/ittnotify/jitprofiling.c
For function `LoadLibraryExA` if `lpFileName` specifies a relative path with LOAD_WITH_ALTERED_SEARCH_PATH flag set, the behavior is undefined. 
Changes are related to adding a check for the relative path before calling function `LoadLibraryExA`.
Jenkins green build: [link](https://cje-ba-prod01.devtools.intel.com/satg-dse-ae/job/Products/job/VTune/job/parameterized-orchestrator/867/)
=> Fix unsecure loading library pointed by ENV variable

.github/workflows/release.yml
After upgrading the `upload-artifact` action from v3 to v4 the release creation workflow was broken (see https://github.com/intel/ittapi/issues/126).
These changes adapt our release workflow to have a unique os-based name for each uploaded artifact and filter downloads by name pattern regarding the migration document: https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact
Also exclude PT support from the macOS build since the latest macOS images are on arm architecture (PT is only supported on x86)
=> ci: fix creating releases job

src/ittnotify/jitprofiling.c
To make `isValidAbsolutePath` function more secure use the `strnlen` function instead of the `strlen`.
Calling the `strlen` function can potentially be unsafe. The `strlen` function calculates the length of a string by counting characters until it reaches a null character and if the string is not properly null-terminated then `strlen` will continue reading memory beyond the end of the string, which can lead to undefined behavior or a program crash.
=> Make the isValidAbsolutePath function more secure by using strnlen

rust/integration-tests/README.md, rust/integration-tests/tests/main.rs, rust/ittapi/src/collection_control.rs, rust/ittapi/src/domain.rs, rust/ittapi/src/event.rs, rust/ittapi/src/jit.rs, rust/ittapi/src/string.rs, rust/ittapi/src/task.rs
This tweaks the links printed in the Rust documentation to point to the latest version of the API, v2024.1.
=> rust: update links to VTune user guide

rust/integration-tests/README.md, rust/integration-tests/tests/main.rs, rust/ittapi/src/collection_control.rs, rust/ittapi/src/domain.rs, rust/ittapi/src/event.rs, rust/ittapi/src/jit.rs, rust/ittapi/src/region.rs, rust/ittapi/src/string.rs, rust/ittapi/src/task.rs
As @Andy51 recommended in #147, this switches the VTune documentation links in the Rust doc comments to use
`...vtune-profiler/user-guide/current/...` instead of a more specific version. Ideally this will keep those links live for longer without requiring us to remember to update them.
=> rust: use evergreen URL for doc links

include/AdvisorAnnotate.cs, include/fortran/advisor_annotate.f90, include/fortran/posix/ittnotify.f90, include/fortran/win32/ittnotify.f90
It seems that we just forgot to change the header copyright in these files after we added them to this repository.
Fix for the related issue https://github.com/intel/ittapi/issues/149
=> Update header copyright info for advisor related files

.github/workflows/release.yml
Added release workflow to add ittapi python wheels in to ittapi release package.
Added wheels for the following configurations:
- CPython versions 3.8-3.12
- Linux/Windows 64-bits
=> ci: add release workflow to include ittapi wheels in release package

.github/workflows/release.yml
Update the release workflow YAML file to include the signing process to be fully compliant with OSSF scorecard policy.
If users want to verify the downloaded release, they can do it via [gh tool](https://github.com/cli/cli):
`gh attestation verify ittapi_build_<release_number>.zip -R intel/ittapi`
https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds
=> ci: add signing step to release workflow

CONTRIBUTING.md, README.md
Small improvements for our documentations:
- Add contributing guide to involve new contributors
- Update README file:
- Add contributing section to README file
- Add CI/CodeQL/OpenSSF scorecard badges to demonstrate product health status
- Add conda-forge/PyPI/crates.io badges to help users to easier get the latest product version
Badges bar:
=> doc: add contributing guide and badges bar

.github/workflows/codeql.yml
This adds a new analysis job to run Rust's code quality analyzer, `rust-clippy`, and upload the JSON results to GitHub's CodeQL service. This template was suggested by GitHub itself and I've modified it to fit our repository; let's see how this goes.
=> ci: run `rust-clippy`, send results to CodeQL

.github/workflows/codeql.yml
Looking at the first Rust code scan issue ([#1]), it looks like it can't show the preview because of a directory issue. Because the Rust crates are in a sub-directory, `rust`, to get proper previews we need to prepend that directory, accomplished here by a simple `sed` replacement.
[#1]: https://github.com/intel/ittapi/security/code-scanning/1
=> ci: fix clippy's CodeQL messages

rust/ittapi/src/jit.rs
This should resolve CodeQL's [#2] warning.
[#2]: https://github.com/intel/ittapi/security/code-scanning/2
=> rust: fix clippy nit

.github/workflows/codeql.yml, src/ittnotify/ittnotify_static.c, src/ittnotify_refcol/README.md, src/ittnotify_refcol/itt_refcol_impl.c
This PR includes the following minor changes:
- Updated the CodeQL GitHub Actions to pin specific versions by hash as required by security rules and deleted not needed autogenerated comments from the workflow file.
- Updated comments and documentation to use the full name "Instrumentation and Tracing Technology API (ITT API)" on the first mention, in accordance with Intel trademark rules.
=> Minor changes to pin GitHub Action versions and align text with trademark rules

src/ittnotify/ittptmark32.S, src/ittnotify/ittptmark32.asm, src/ittnotify/ittptmark64.S, src/ittnotify/ittptmark64.asm
Starting with [binutils 2.39](https://lists.gnu.org/archive/html/info-gnu/2022-08/msg00002.html):
> The ELF linker will now generate a warning message if the stack is made executable. Similarly it will warn if the output binary contains a segment with all three of the read, write and execute permission bits set. These warnings are intended to help developers identify programs which might be vulnerable to attack via these executable memory regions.
Normally, the stack is marked as non-executable by the C compiler, but when you are using raw assembly it gets marked as executable, the assumption being that assembly authors want an executable stack. Adding the `.note.GNU-stack` section at the bottom of the .s files tells the linker the stack shouldn't be executable.
Updated header copyrights …
=> Force non-executable stack for assembly object files on Linux

src/ittnotify/ittnotify_static.c
Some projects that include oneDNN use `-Wundef` compilation flag. oneDNN decided to add the flag into the build as well and it automatically promoted to third_party dependencies including ittnotify.
Macros that may not be defined must be checked for presence first.
=> src: ittnotify: ittnotify_static: resolve Wundef hits

src/ittnotify_refcol/Makefile, src/ittnotify_refcol/itt_refcol_impl.c
Implemented creation and management of ITT API domains, string handles, counters, and histograms objects in the reference collector. As well fixed some minor problems in reference collector.
These changes should improve the usability of the reference collector and solve problems such as https://github.com/intel/ittapi/issues/178
=> Add ITT API object creation and cleanup to reference collector

src/ittnotify_refcol/itt_refcol_impl.c
Improve performance by keeping the log file open during application lifecycle rather than reopening it for each log entry. The cleanup function has been registered with atexit() to ensure proper resource release.
=> Improve reference collector performance

docs/src/itt-api-reference.rst, docs/src/ittapi/formatted-metadata-api.rst, docs/src/ittapi/task-api.rst
Add new page into the public ITTAPI documentation.
Add usage and description for Formatted Metadata API for tasks.
=> doc: add Formatted Metadata API documentation
